# Load in NumPy(pip install numpy)

In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9,8,7],[4,5,6]])
print(b)

[[9 8 7]
 [4 5 6]]


In [6]:
# Get the dimensions
a.ndim


1

In [7]:
# Get the shape of the array 
b.shape

(2, 3)

## Accessing/Changing specific elements, rows, & columns

In [14]:
a = np.array([[3,4,5,6,7,8,9,10],[34,12,45,12,56,12,34,65]])
print(a)

[[ 3  4  5  6  7  8  9 10]
 [34 12 45 12 56 12 34 65]]


In [16]:
# get a specific element 
# use the [r,c] notation
a[1, 4]

56

In [18]:
# get a specific row
a[0,:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# get a specific column
a[:,2]

array([ 5, 45])

In [36]:
# exercising on stepping 
a[0,2:7:2]
a[0,1:7:4]

array([4, 8])

## 3D Array

In [38]:
a = np.array([[[1,2],[4,5]],[[6,9],[8,3]]])
print(a)

[[[1 2]
  [4 5]]

 [[6 9]
  [8 3]]]


In [40]:
# Get specific elements
a[1,0,1]
a[0,:]

array([[1, 2],
       [4, 5]])

## Initializing different types of array

In [45]:
# All zeros matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# All ones matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [52]:
# Any other number
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [53]:
# Random Numbers
np.random.rand(4,2)

array([[0.8912834 , 0.47973811],
       [0.48603283, 0.63368348],
       [0.59349251, 0.19113394],
       [0.39280392, 0.97844269]])

In [65]:
output = np.ones((5,5))

z = np.zeros((3,3))

z[1,1] = 9

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [75]:
data = np.array([[2,3],[4,5]])
ones = np.ones((2,2))

data + ones


array([[3., 4.],
       [5., 6.]])

## Unique items and counts

In [78]:
# Get unique elements in an array
a = np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])

# To get the index of the unique values pass return_index=True as an argument
# To get the frequency count pass return_counts=True

unique_values = np.unique(a, return_index=True, return_counts=True)
print(unique_values)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]), array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))


## Transposing and Reshaping

In [88]:
a = np.array([[2,5],[8,6],[3,4]])

print(a)

# Reshaping an array use arr.reshape()
a.reshape(2,3)



[[2 5]
 [8 6]
 [3 4]]


array([[2, 5, 8],
       [6, 3, 4]])

In [86]:
#To transpose a matrix use arr.T()
a.transpose()

array([[2, 8, 3],
       [5, 6, 4]])

## Reversing an Array

In [89]:
# To reverse an array use np.flip()
a = np.array([1,2,3,4,5,6,7,8])

reverse = np.flip(a)
print(reverse)

[8 7 6 5 4 3 2 1]


In [91]:
# also works with a 2D array
a_2d = np.array([[2,3,4],[5,6,7],[8,9,10]])
reversed = np.flip(a_2d)

print(reversed)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


 To reverse a specific row or column make use of axis 
 
 For columns set the axis to 1 
 
 For rows set the axis to 0

In [94]:
# column
reverse_column = np.flip(a_2d, axis=1)

print(reverse_column)

[[ 4  3  2]
 [ 7  6  5]
 [10  9  8]]


In [95]:
# row
reverse_row = np.flip(a_2d, axis=0)

print(reverse_row)

[[ 8  9 10]
 [ 5  6  7]
 [ 2  3  4]]
